# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a039395ad441cd424242a3ad45b50c089d1b011001f0cd4e0e80c05d143e18aa0e382b427c03155ef1bc3bf9d4045a3c6ae4cfa6c9fd93cb9596610c3c6ca85

test:
  secret_key_base: dc7839135566d5149d50de082face53850803527ed399e81cb5422d63c8371c631a271f82504490df8774c3223bb4bfbcc73e29cc087ebf5a43b648db872e03b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
